### ISSUE TITLE
Setup new relic monitoring

### ISSUE THREAD

**Issue by jmhooper** [18F/analytics-reporter-api#1]
We have a new relic account, but we do not have monitoring setup for the API.

**Comment by jmhooper** [comment]
Uptime monitoring is configured. I still need to configure exception monitoring.

**Comment by ryanhofdotgov** [comment]
@tdlowden Can you tell from your New Relic dashboard access if this issue is still outstanding? New Relic is configured in the other 2 components based on these artifacts: [web app](https://github.com/18F/analytics.usa.gov/blob/d140e47d15adb8cd49081c530777bfae3ec013fb/compliance/component.yaml), [analytics reporter](https://github.com/18F/analytics-reporter/blob/0821d3d67c1820a49a89e4e98f6b223cfc3b9555/deploy/cron.js)

**Comment by tdlowden** [comment]
As far as I can tell from the dashboard, we only have the reporter being monitored atm
![image](https://user-images.githubusercontent.com/6556888/73455527-40a7e600-433e-11ea-8b58-64cfd00672ab.png)

**Comment by levinmr** [comment]
done

**Comment by tdlowden** [comment]
Out here closing 7 year old issues! Bravo 😆
